# Site settings
title: Teknord
email: teknord@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Our products are coming soon!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Teknord
github_username:  teknord

# Build settings
markdown: kramdown
